In [1]:
%pip install statsmodels

Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
     |████████████████████████████████| 8.1MB 4.0MB/s eta 0:00:01  |████████▉                       | 2.3MB 4.0MB/s eta 0:00:02██████▏              | 4.3MB 4.0MB/s eta 0:00:01B/s eta 0:00:01██████████████████████████████▋| 8.0MB 4.0MB/s eta 0:00:01
     |████████████████████████████████| 235kB 55.8MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [54]:
# 并生成正态分布的二维数组5*4
import numpy as np
arr= np.array([[1,2,3],
               [1,2,3],
               [7,8,9]])# normally-distributed data 
print(arr)
print(arr.mean(), np.mean(arr))# 算术平均
print(arr.sum(), np.sum(arr))# 求和
print(arr.std(), np.std(arr))#标准差
print(arr.argmin(), arr.argmax())#最大最小值索引

[[1 2 3]
 [1 2 3]
 [7 8 9]]
4.0 4.0
36 36
2.943920288775949 2.943920288775949
0 8


In [54]:
print(arr[0])
print(arr[:,0])
print(arr.sum(0))# 求第一维(列和)
print(arr.mean(0))
print(arr.sum(1))
print(arr.cumsum(0))# 列元素累计和
print(arr.cumprod(0))# 列元素累乘

[1 2 3]
[1 1 7]
[ 9 12 15]
[3. 4. 5.]
[ 6  6 24]
[[ 1  2  3]
 [ 2  4  6]
 [ 9 12 15]]
[[ 1  2  3]
 [ 1  4  9]
 [ 7 32 81]]


In [5]:
import numpy as np
a= np.array([[1,2,3],
             [1,2,3],
             [7,8,9]])
print(a * a)

[[ 1  4  9]
 [ 1  4  9]
 [49 64 81]]


In [6]:
import scipy
from scipy import linalg
b = a * a

In [7]:
a = scipy.mat(a)
b = a * a
print(b)
print(type(b))

[[ 24  30  36]
 [ 24  30  36]
 [ 78 102 126]]
<class 'numpy.matrix'>


/root/anaconda3/envs/DataMining/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: scipy.mat is deprecated and will be removed in SciPy 2.0.0, use numpy.mat instead
  """Entry point for launching an IPython kernel.


In [9]:
import numpy as np
import scipy
from scipy import linalg
a = np.array([[1, 2, 3], [4, 5, 6], [0, 0, 1]])
ma = scipy.mat(a) * scipy.mat(a)
mb = linalg.inv(ma)
print(mb)

[[ 3.66666667 -1.33333333 -2.        ]
 [-2.66666667  1.          0.        ]
 [ 0.          0.          1.        ]]


/root/anaconda3/envs/DataMining/lib/python3.7/site-packages/ipykernel_launcher.py:5: DeprecationWarning: scipy.mat is deprecated and will be removed in SciPy 2.0.0, use numpy.mat instead
  """


In [10]:
ma * mb

matrix([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [4.88498131e-15, 1.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [11]:
import sklearn
sklearn.__version__

'0.22'

In [12]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
print(model)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)


In [14]:
from sklearn import datasets
iris = datasets.load_iris() # load data set
print(iris.data.shape)

(150, 4)


In [15]:
b = datasets.load_boston()
print(b.data.shape)

(506, 13)


In [19]:
print(iris.data[:15])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]]


In [24]:
iris.target[:5000]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [28]:
from sklearn import svm
clf = svm.LinearSVC()
clf.fit(iris.data, iris.target)
clf.coef_

/root/anaconda3/envs/DataMining/lib/python3.7/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


array([[ 0.18424051,  0.45122993, -0.8079406 , -0.45071484],
       [ 0.05602469, -0.89814113,  0.40855797, -0.96070759],
       [-0.85071544, -0.98672207,  1.38104133,  1.86533957]])

In [29]:
clf.predict([[5, 3.6, 1.3, 0.25]])

array([0])

In [ ]:
clf.predict([[5, 1.6, 2.3, 1.95]])

In [36]:
%conda install keras

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.6.11
  latest version: 4.8.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /root/anaconda3/envs/DataMining

  added / updated specs:
    - keras


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _tflow_select-2.3.0        |              mkl           2 KB
    absl-py-0.8.1              |           py37_0         161 KB
    astor-0.8.0                |           py37_0          45 KB
    c-ares-1.15.0              |    h7b6447c_1001         102 KB
    gast-0.2.2                 |           py37_0         137 KB
    google-pasta-0.1.8         |             py_0          43 KB
    grpcio-1.16.1              |   py37hf8bcb03_1         1.0 MB
    intel-openmp-2019.4        |              243         876 KB
    keras-2

In [38]:
%conda install tensorflow

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.6.11
  latest version: 4.8.0

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [41]:
%%system 
conda list keras

['WARNING: The conda.compat module is deprecated and will be removed in a future release.',
 '# packages in environment at /root/anaconda3:',
 '#',
 '# Name                    Version                   Build  Channel']

# LSTM

In [2]:
#!/opt/anaconda2/bin/python
# -*- coding: utf-8 -*-
from keras.models import Sequential
from keras.layers import LSTM, Dense
import numpy as np
import codecs,csv

data_dim = 16
timesteps = 8
nb_classes = 10
filename = "LSTM-Outputs.txt"

# 简单搭建一个LSTM
model = Sequential()  # 模型初始化
# expected input data shape: (batch_size, timesteps, data_dim)
model.add(LSTM(32, return_sequences=True,
               input_shape=(timesteps, data_dim)))  # returns a sequence of vectors of dimension 32
model.add(LSTM(32, return_sequences=True))  # returns a sequence of vectors of dimension 32
model.add(LSTM(32))  # return a single vector of dimension 32
model.add(Dense(10, activation='softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

# 生成训练数据
x_train = np.random.random((1000, timesteps, data_dim))
y_train = np.random.random((1000, nb_classes))
# 生成验证数据
x_val = np.random.random((100, timesteps, data_dim))
y_val = np.random.random((100, nb_classes))
# 生成验证数据
x_test = np.random.random((100, timesteps, data_dim))
y_test = np.random.random((100, nb_classes))

# 训练模型
model.fit(x_train, y_train, batch_size=64, nb_epoch=5,validation_data=(x_val, y_val))
# 预测结果
results = model.predict(x_test, batch_size=32, verbose=0)
# 保存预测结果

with codecs.open(filename, 'w', encoding='utf-8') as f:
    f_csv = csv.writer(f)
    f_csv.writerows(results)
		
score = model.evaluate(x_test, y_test, batch_size=16) # 在test数据上评估模型
print("\nEvaluation Metrics：\n", model.metrics_names)
print(score)

Using TensorFlow backend.


/root/anaconda3/envs/DataMining/lib/python3.7/site-packages/ipykernel_launcher.py:37: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Train on 1000 samples, validate on 100 samples
Epoch 1/5





1000/1000 [==============================] - 9s 9ms/step - loss: 11.5995 - acc: 0.0960 - val_loss: 11.4651 - val_acc: 0.0900
Epoch 2/5
1000/1000 [==============================] - 1s 848us/step - loss: 11.5977 - acc: 0.1060 - val_loss: 11.4673 - val_acc: 0.0900
Epoch 3/5
1000/1000 [==============================] - 1s 864us/step - loss: 11.5972 - acc: 0.1120 - val_loss: 11.4653 - val_acc: 0.0800
Epoch 4/5
1000/1000 [==============================] - 1s 871us/step - loss: 11.5964 - acc: 0.1260 - val_loss: 11.4655 - val_acc: 0.0600
Epoch 5/5
100/100 [==============================] - 0s 468us/step

Evaluation Metrics：
 ['loss', 'acc']
[11.597126083374024, 0.14]


In [8]:
%system cat LSTM-Outputs.txt

['0.09872068,0.09909036,0.09756784,0.09945232,0.10149519,0.10359305,0.099014565,0.10153909,0.09785472,0.1016722',
 '0.09937414,0.100764,0.099050455,0.09911605,0.10260559,0.098768845,0.09794066,0.102878764,0.1011187,0.09838283',
 '0.09886286,0.100745805,0.096850514,0.10006168,0.099311605,0.10468718,0.09876649,0.101973556,0.099417,0.099323355',
 '0.099056385,0.10048284,0.09914506,0.09905165,0.10292029,0.09992832,0.09831045,0.102226384,0.09986881,0.099009864',
 '0.09854326,0.10131999,0.09803644,0.09851867,0.101614624,0.09903499,0.09908958,0.104178354,0.10080119,0.09886297',
 '0.098771684,0.103383146,0.097573385,0.0977823,0.100144275,0.09767992,0.10029391,0.10374808,0.10116958,0.09945368',
 '0.09882819,0.09932422,0.09774982,0.09845453,0.10100934,0.10342102,0.09920906,0.101848826,0.0984874,0.10166763',
 '0.099211805,0.10015796,0.09954198,0.099020086,0.103398845,0.09883519,0.09844154,0.102016576,0.10008279,0.099293195',
 '0.0983323,0.09943401,0.09564061,0.100873224,0.098280616,0.1094855,0.09